### ISSUE TITLE
Dependency on enum34 breaks python  3.7 (and proabably 3.6) - is it possible to make it a conditional dependency

### ISSUE THREAD

**Issue by Ancient87** [palantir/conjure-python-client#100]
## What happened?

I was trying to integrate the conjure generated python classes into my Python3.7.5 environment, and hit an issue. It seem that enum34 breaks newer versions of setuptools as discussed in detail  [here](https://github.com/python-poetry/poetry/issues/1122) and [here](https://stackoverflow.com/questions/45896474/installing-enum34-on-python-3-x-breaks-pip-for-python3-x). As both conjure-python-client and the generated classes themselves list enum34 as a dependency Installing the package into my project breaks pip.

For now I had to end up manually scripting/editing the dependency in my generated class files, and "vendor" "conjure-python-client" which is clearly not ideal.

## What did you want to happen?

Perhaps it would be an easy fix to replace the dependency with a conditional such as '"enum34; python_version < "3.4"'

Many thanks

**Comment by Latios96** [comment]
Hi,

I have the same issue as you describe.

There is a pull request [here](https://github.com/palantir/conjure-python-client/pull/99) fixing this issue, but it was not merged yet.
Would it be possible to merge this pull request? Is there something missing that prevents merging this?

**Comment by robert3005** [comment]
Fixed in 2.x (there's also conjure-python 4.x that uses it)
